### ISSUE TITLE
[BUG] Android App crashes when phone allowed two SMS at the same time.

### ISSUE THREAD

**Issue by dalerugs** [surfstudio/flutter-otp-autofill#10]
## Describe the bug

When the android phone receives two SMS at the same time, and the user allows the two OTPs, the app crashes.
Below is the error found in the logs.

```dart
E/AndroidRuntime( 4770): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { (has extras) }} to activity {com.sample.app/com.sample.app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 4770): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5506)
E/AndroidRuntime( 4770): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547)
E/AndroidRuntime( 4770): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 4770): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 4770): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 4770): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime( 4770): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4770): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime( 4770): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
E/AndroidRuntime( 4770): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4770): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime( 4770): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime( 4770): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 4770): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/AndroidRuntime( 4770): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 4770): 	at ru.surfstudio.otp_autofill.OTPPlugin.onActivityResult(OTPPlugin.kt:122)
E/AndroidRuntime( 4770): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
E/AndroidRuntime( 4770): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime( 4770): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
E/AndroidRuntime( 4770): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:651)
E/AndroidRuntime( 4770): 	at android.app.Activity.dispatchActivityResult(Activity.java:8541)
E/AndroidRuntime( 4770): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5499)
E/AndroidRuntime( 4770): 	... 11 more
I/Process ( 4770): Sending signal. PID: 4770 SIG: 9
```

## Steps to Reproduce

1. Send SMS to the phone at the same time.
2. Two user consent modals will show.
3. Click the allow button on the two modals.

## What is the expected behavior?

The app should not crash when clicking the allow button and the latest OTP must be displayed on the field.

**Comment by dalerugs** [comment]
Hi, any updates on this issue? Thank you.

**Comment by dalerugs** [comment]
Hi, any updates on this issue? Thank you.

**Comment by MbIXjkee** [comment]
Thx for issue, looks like bug in native part, we will check is it trouble in our part or system.

**Comment by MbIXjkee** [comment]
@dalerugs Can you add code example to reproduce behavior which you get? You get this on every device? We try to reproduce it, but get only one modal. Need more information.

**Comment by internetova** [comment]
Hello @dalerugs,

We tried to reproduce described error but we failed. However, we managed to get similar error in console while incorrect subscription initialization. We have suspicions that you could write an incorrect code and we would like to help to resolve it.

Can you please provide us with the following data:

1. Code for error reproduction.
2. What simulator or emulator was used with the operating system?
3. If you used phone, what was the model of the phone and what operating system is installed of the phone where error occurred?
4. Flutter doctor.
5. Video record of an error.

Thank you.

**Comment by wesam-salama** [comment]
I/flutter (19097): signature - 0VH2py/xFgh
I/Timeline(19097): Timeline: Activity_launch_request time:593250429
I/Timeline(19097): Timeline: Activity_launch_request time:593250439
V/PhoneWindow(19097): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@6e7ac29, this = DecorView@7cefbae[MainActivity]
I/flutter (19097): Your Application receive code - 1308
I/Timeline(19097): Timeline: Activity_launch_request time:593278665
D/AndroidRuntime(19097): Shutting down VM
E/AndroidRuntime(19097): FATAL EXCEPTION: main
E/AndroidRuntime(19097): Process: ru.surfstudio.otp_autofill, PID: 19097
E/AndroidRuntime(19097): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { (has extras) }} to activity {ru.surfstudio.otp_autofill/ru.surfstudio.otp_autofill_example.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(19097): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5195)
E/AndroidRuntime(19097): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5236)
E/AndroidRuntime(19097): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(19097): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(19097): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(19097): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
E/AndroidRuntime(19097): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19097): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(19097): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/AndroidRuntime(19097): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19097): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/AndroidRuntime(19097): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/AndroidRuntime(19097): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(19097): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime(19097): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(19097): 	at ru.surfstudio.otp_autofill.OTPPlugin.onActivityResult(OTPPlugin.kt:122)
E/AndroidRuntime(19097): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
E/AndroidRuntime(19097): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
E/AndroidRuntime(19097): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
E/AndroidRuntime(19097): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
E/AndroidRuntime(19097): 	at android.app.Activity.dispatchActivityResult(Activity.java:8516)
E/AndroidRuntime(19097): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5188)
E/AndroidRuntime(19097): 	... 11 more
I/Process (19097): Sending signal. PID: 19097 SIG: 9
Lost connection to device.

- My device is: xiaomi redmi note 8 pro.
- I use the example Code.
- Flutter doctor
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale
    en-PS)
    • Flutter version 2.10.0 at /Users/wesamsalama/Flutter/flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (4 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wesamsalama/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Redmi Note 8 Pro (mobile) • aaaqof8xhuqwmrdi • android-arm64  • Android 11
      (API 30)
    • Chrome (web)              • chrome           • web-javascript • Google
      Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

![telegram-cloud-photo-size-4-5834665866086692683-y](https://user-images.githubusercontent.com/56071978/156360301-bfb463a2-985a-45dc-b74d-8c2424731899.jpg)

**Comment by wesam-salama** [comment]
- bug senario is:
1 - Resave the first code and press allow ( controller will filled with code)
2 - Resave the second code , when i press allow the app will craches

**Comment by kipkemoifred** [comment]
i got the errors too, when 2sms sends otp to phone at the same time.
- also when the listen for otp  method fails to get otp. then otp arrives later it crashes.

**Comment by BLUECALF** [comment]
- i got same issue , when 2 otp arrives it crash.
- mine when otp doesnt arrive in the expected time. then it arrives later the app crashes.
- its like the method stoplistsen for otp does not work.

**Comment by jale-codex** [comment]
Any update? Absolutely the same situation here. Receive the code for the first time, then on the second one the app crashes

**Comment by BLUECALF** [comment]
If you are using  retriever that needs the app signature at SMS , the only solution I got is to use other package.

**Comment by BLUECALF** [comment]
I used sms_autofil package and it worked even with spamming sms. App did not crash.
