### ISSUE TITLE
[BUG]  OTP AutoFill hint

### ISSUE THREAD

**Issue by rGradov** [surfstudio/flutter-otp-autofill#9]
When i tried to implement hint (for number) isn't work. I see popup and then he quickly closed.
``` Dart

  @override
  void initState() {
    // TODO: implement initState
    saveCurrentRoute('$PhoneConnection');
    setRouteArray('$PhoneConnection', true);
    Future.delayed(Duration(milliseconds: 2000))
        .then((value) async => await getNumber());
    super.initState();
  }
```
``` Dart
Future<dynamic> getNumber() async {
    var _otpInteractor = OTPInteractor();
    String number = await _otpInteractor.hint;
    debugPrint('$number');
  }
```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.258], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.0 RC2)
[!] Android Studio (not installed)
[√] VS Code (version 1.61.2)
[√] Connected device (4 available)

! Doctor found issues in 1 category.

```

**Comment by internetova** [comment]
Hello @rGradov,

We tried to reproduce described error on the similar telephone - Huawei p20 like, but we failed.
Thank you for provided additional information.

**Comment by feduke-nukem** [comment]
Hello @rGradov,

In order to resolve this issue, we'd like to get more details on it, such as device model or full case issue-code.

Unfortunately, provided code above didn't failure within our checks, so we aren't able to identify the problem.

Also we'd like to mention that phone number hint feature relies on sim-card based contacts. Thus, we can assume that in your case the issue could have arisen because of this.

We'd like to help you further if issue persists.
